-- furisrv database schema

CREATE TABLE IF NOT EXISTS Users (
  Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  Password TEXT NOT NULL,
  Name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS Devices (
  Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  Password TEXT NOT NULL,
  OwnerId INTEGER NOT NULL,
  Name TEXT NOT NULL,
  FOREIGN KEY ( OwnerId )
    REFERENCES Users ( Id )
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Sensors (
  Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  DeviceId INTEGER NOT NULL,
  SensorIndex INTEGER NOT NULL,
  Name INTEGER NOT NULL,
  UNIQUE ( DeviceId, SensorIndex ),
  FOREIGN KEY ( DeviceId )
    REFERENCES Devices ( Id )
    ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS Scripts (
  Id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  DeviceId INTEGER NULL,
  Script TEXT NOT NULL,
  FOREIGN KEY ( DeviceId )
    REFERENCES Devices ( Id )
    ON UPDATE CASCADE ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ScriptSensors (
  ScriptId INTEGER NOT NULL,
  SensorId INTEGER NOT NULL,
  Name TEXT NOT NULL,
  PRIMARY KEY ( ScriptId, SensorId ),
  FOREIGN KEY ( ScriptId )
    REFERENCES Scripts ( Id )
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY ( SensorId )
    REFERENCES Sensors ( Id )
    ON UPDATE CASCADE ON DELETE CASCADE
);
